[project]
name = "presto-demo"
version = "0.1.0"
authors = [
    {name = "Intermodulation Products AB", email = "support@intermod.pro"},
]
description = "Demo scripts for the Presto platform runnable in loop-back"
license = "MIT"
requires-python = ">= 3.10"
dependencies = [
    "numpy >= 1.24",
]

[tool.black]
line-length = 99

[tool.pylint.format]
max-line-length = 99

[tool.pyright]
typeCheckingMode = "standard"
deprecateTypingAliases = true
reportDeprecated = "warning"
reportMissingImports = false

[tool.ruff]
line-length = 99

[tool.yapf]
based_on_style = "pep8"
column_limit = 99

[dependency-groups]
dev = [
    "basedpyright>=1.34.0",
]

